spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/lilleplaces
spring.datasource.username=postgres
spring.datasource.password=password
jwt.secret=OtNxTkYxm8FM84oY8AMUD2UAxHpN2Uw/9UhPEF7nxv0=
